language: node_js
node_js:
- node
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  provider: surge
  project: ./build/
  domain: zelda-cookbook.surge.sh
  skip-cleanup: true
  secure: LwHTt7Xekbd5OCft+aYxdzw2Ff9p03NjNafwjhtJIwPn8fo/o4yFSJ3lApBdC2RdByVSsxsKqYg2r9x1PXEqywwbmkhw9GQFKtOENN+wd7oNgD4FAqr2sm+42maad0Ks3Ce3Xe0YMmzjnSR78Nh5vPnIxcfIffubuYx7u/UnGB8iz8wTtpCTV6xu8igQgg+vjETGIKX2Y82twzPQDxJvBAPWWLXBtS42r3V3faHicKU0XxH7utBaugS+wHZFBbjfDUeFILOf5+nBgbaxxI0xswboxoo12xV+Nk30Itw5aK9OBvDwHd0/w5F/p1ebVoBjFd3UmWg5lmvR6sgznMgtVht1AYB9R2e5mjf14K9uSmOnD7ydmOr8BzlBWXxbkaBaTqDEeO+jFhappyW9vSkLHn9JpGdy+WNXMgjP9zObI/tB0DHdmoT880FubeMdISwpE3GS/dVKAxj07qisZrc/qj3TjYsWAO0oMcyDQDtfKwsCdau9yFrh1207RC7wpJ11OY14HfDW/3I2VYyOBAUEVR6MOTAiks2/n74DOGNQGnWN5yf9jXYW/rEVVpfpNKoP4lThzLy4zTWoVmwhd+FoWfBiy5lBgPo63bBAKu2o2Q4UgKHmYOarCLlO5m3JSiAu63uSolI9lpACJ9VWBazBksoVrHbCkD4Bc3xlILSUtn4=
